
services:
  dockerized_db:
    image: postgres
    restart: always
    env_file:
      - development.env
    ports:
      - "5432:5432"
    volumes:
      - dockerized_postgres_data_storage:/var/lib/postgresql/data/pgdata

  dockerized_redis:
    image: redis:6.2
    restart: always
    env_file:
      - development.env
    ports:
      - "6379:6379"
    volumes:
      - dockerized_redis_data:/data

volumes:
  dockerized_postgres_data_storage:
  dockerized_redis_data: